### ISSUE TITLE
Wrong case for image names in retroHeroToIcon(), I think

### ISSUE THREAD

**Issue by m-e-meyer** [Loathing-Associates-Scripting-Society/ChIT#1]
# Context

## Browser

Google Chrome in a Fedora Linux environment

## ChIT Settings Changes

none

# Behavior

In ChIT, the retro superhero cape appears as a broken image.  The problem goes away if I edit my copy of chit_brickGear.ash so that the image names in retroHeroToIcon() each start with lowercase r instead of uppercase R.

**Comment by soolar** [comment]
That makes sense, I've been working on it on a non-case sensitive platform. I'll have a fix out for this tomorrow (I'd do it now if I wasn't about to go to sleep) :)

**Comment by soolar** [comment]
Fixed with 1bfb35de6f704d964c83169b2d1ef97ecbdde504

That'll teach me to check the wiki for image names instead of just looking in the itemimages folder on my machine.
