### ISSUE TITLE
Flase failure message on uninstall.

### ISSUE THREAD

**Issue by djve60** [Loathing-Associates-Scripting-Society/ChIT#24]
# Prerequisites

All checked.

# Context

On `git delete ChIT` get the bogus error "Failed to completely remove project Loathing-Associates-Scripting-Society-ChIT"

## Browser

Firefox 105.0

## ChIT Settings Changes

None. Trying the delete and install before submitting a bug and hit this issue on "git delete ChIT".

# Expected/Desired Behavior

Clean message on project deletion.

Details:

Removing project Loathing-Associates-Scripting-Society-ChIT
data/chit_effects.txt => DELETED
data/chit_ReadMe.Txt => DELETED
data/chit_GearCategories.txt => DELETED
images/relayimages/chit/update.png => DELETED
....
images/relayimages/chit/application_xp_terminal.png => DELETED
images/relayimages/chit => DELETED
**images/relayimages failed to delete**
relay/chit_xiblaxian.ash => DELETED
...
relay/chit.css => DELETED
relay/charpane.ash => DELETED
Failed to completely remove project Loathing-Associates-Scripting-Society-ChIT

I'm glad it did not delete images/realyimages but it should not have an error message for this either.

Now to reinstall and see if my bug still exists, after restarting, etc.

**Comment by soolar** [comment]
This sounds more like a mafia issue to me, but I'm not 100% certain yet.

**Comment by midgleyc** [comment]
If `images/relayimages` contains non-chit files (i.e. the folder is not empty when you're requesting it to be deleted) this is a mafia bug: when implementing I assumed any folders would contain only items relevant to one script, which is not necessarily true.

**Comment by djve60** [comment]
It had no non-chit files as I was going over the steps for logging the other issue (PVP fights not showing up) and went through the process twice to make sure I documented it.
But I had to start somewhere. Makes sense for this to be a Mafia bug. You should probably close this down as a non-bug.
