### ISSUE TITLE
"git delete ChIT" does not delete git download dir on Ubuntu 22.04.

### ISSUE THREAD

**Issue by djve60** [Loathing-Associates-Scripting-Society/ChIT#25]
# Prerequisites

Prerequisites all done.

# Context

Reinstall of ChIT as requested in the prerequisites.

## Browser

Firefox 105.0 but it's not relevantto this issue.

## ChIT Settings Changes

None.

# Expected/Desired Behavior

Installation of ChIT to succeed after `git delete ChIT` has been issued.

# Current Behavior

```
> git checkout https://github.com/Loathing-Associates-Scripting-Society/ChIT.git
Cannot clone project to Loathing-Associates-Scripting-Society-ChIT, folder already exists. Please delete to checkout.

```

Other details:
Installation works after manual removal of files downloaded from github.

**Comment by soolar** [comment]
This one is definitely an issue with mafia's `git` command, not with ChIT itself.
