### ISSUE TITLE
Effects list does not display anything

### ISSUE THREAD

**Issue by PKPenguin321** [Loathing-Associates-Scripting-Society/ChIT#5]
# Context

After updating mafia from KoLmafia-25935 to KoLmafia-26001, the effects list has stopped displaying anything. I then updated ChIT to the latest version + restarted mafia and my browser, but the issue persisted.

## Browser

Google Chrome

## ChIT Settings Changes

Describe any changes you've made to your ChIT settings here. If you don't remember if you have, try `prefref chit.` in
KoLMafia's Graphical CLI (the "." is important) and note any settings that do not start with "DEFAULT:"

_glitchItemImplemented = true (along with several other glitchItem-related settings)

chit.gear.favorites = [all my favorited items]

chit.notifyShenanigans.done = true

# Expected/Desired Behavior

To see my effects and buttons to recast them and stuff

# Current Behavior

The rows for each effect appear but are blank

# Screenshot(s)

![image](https://user-images.githubusercontent.com/8345184/146121966-99a3426a-b608-4db1-82c9-7a2763bb5a60.png)

**Comment by gausie** [comment]
This will be because mafia decorates a new span onto each effect to fix a
safari bug
