### ISSUE TITLE
KoLmafia change broke ChIT's display of effects

### ISSUE THREAD

**Issue by magus-prime** [Loathing-Associates-Scripting-Society/ChIT#8]
This change https://github.com/kolmafia/kolmafia/pull/344 broke ChIT's active effects block.

The reason why is detailed in https://kolmafia.us/threads/charpane-effect-decoration-has-a-new-bug.26962/

As a result versions of KoLmafia >= 26000 have an empty effects block in ChIT.

**Comment by gausie** [comment]
This was fixed in #7 . If you're still seeing the issue try deleting and then reinstalling chit

**Comment by magus-prime** [comment]
That did it.  Thank you.
